version: '3'

services:
    appi_simo:
        image: postgres:11.1
        environment:
            - POSTGRES_USER=CowboysTeam
            - POSTGRES_PASSWORD=CowboysTeam
            - POSTGRES_DB=KingRoger_DEV
        ports:
            - 5432:5432
        volumes:
            - ./data/appi_simo:/var/lib/postgresql
